language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy3.5"
# command to install dependencies
before_script:
  - easy_install distribute
  - pip install -r requirements.txt
install:
  - pip install ./basic_calc
# command to run tests
script: pytest
