language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy3.5"
# command to install dependencies
before_install:
  - easy_install distribute
  - pip install -r requirements.txt
install:
  - pip install ./basic_calc
# command to run tests
script: 
- cd basic_calc
before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "safan41"
      - git config --local user.email "safan25641@gmail.com"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: dist
  skip_cleanup: true
